### ISSUE TITLE
Add SPICEYPY support to OOPS

### ISSUE THREAD

**Issue by jnspitale** [SETI/rms-oops#123]
OOPS could be generalized to work with SPICEYPY fairly easily, closing a potential weakness in our PDART proposal.  Since both packages basically map one-to-one with SPICE calls , this could be achieved by converting the existing CSPYCE calls to wrappers that would determine which package to actually call.  This would also be a step toward the OMINAS/VEMINAS-style translator arrangement where the souce of the geometric data is fully abstracted.

The only code in OOPS that is not using a CSPYCE wrapper to naiflib is the aliases stuff in oops/__init.py__.  My guess is that this would just not be called if using SPICEPY.

**Comment by matthewtiscareno** [comment]
You can mention this potential work in your proposal without doing any further work right now, correct?  So that would alleviate the potential weakness you mention?

**Comment by jnspitale** [comment]
It is probably better to write a SpiceyPy wrapper to CSPYCE.
