### ISSUE TITLE
Missing OOPS_RESOURCES does not cause test failure exit

### ISSUE THREAD

**Issue by rfrenchseti** [SETI/rms-oops#62]
If the `OOPS_RESOURCES` environment variable is not set, running the hosts unit tests gives:

```
runTest (hosts.juno.junocam.Test_Juno_Junocam_GoldMaster) ... 2023-03-13 10:21:47.041622 | oops.backplane.gold_master | CRITICAL | Undefined environment variable: OOPS_RESOURCES
2023-03-13 10:21:47.041695 | oops.backplane.gold_master | INFO  | Total errors = 1
ok
runTest (hosts.solar.unittester.Test_Solar) ... <frozen importlib._bootstrap>:241: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 96 from PyObject
ok

----------------------------------------------------------------------
Ran 2 tests in 1.564s

OK
```

and the coverage report gives:

```
-------------------------------------------------
unittester.py       4      0      0      0   100%
-------------------------------------------------
TOTAL               4      0      0      0   100%
```

Both of these are dangerous outcomes. An automated system could easily conclude that the tests ran perfectly, since they all passed and coverage is at 100%. When `OOPS_RESOURCES` is not defined, the tests should exit with a failure.

Also, why do the hosts tests require `OOPS_RESOURCES` but the Backplane tests only require `OOPS_TEST_DATA_PATH`? Shouldn't there just be one environment variable for all the tests?

**Comment by markshowalter** [comment]
Interesting. In unit tests, the logger counts errors and a the unit test fails if errors > 0. However, this particular error occurs before the logger is initialized. The solution is to wrap all of the code inside execute_as_unittest inside a try clause and add "testcase.assertTrue(False, ...)" before the call to run_tests. I am happy to fix this and the other two inside my current pull request.

**Comment by rfrenchseti** [comment]
This was previously fixed.
