### ISSUE TITLE
Write general tools for index file creation

### ISSUE THREAD

**Issue by jnspitale** [SETI/rms-oops#84]
The programs for generating supplemental index files all do kind of the same thing, and there is a lot of repeated code with minor tweaks (e.g., COUVIS_supplement.py vs. COVIMS_supplement.py, NHxxLO_supplemental_index.py vs. NHxxMV_supplemental_index.py).  A general set of tools for handling these tasks would streamline the creation of new supplemental index files and make the programs more readable.

**Comment by rfrenchseti** [comment]
This should be in the `rms-data-projects` repo and I'm moving it there.
